### PR TITLE
[NBS] add logging to NVMe manager; minor fixes

### LINKED ISSUE #5250: [NBS] Add VFIO-PCI passthrough support for local NVMe devices in QEMU VMs
Currently, NBS can expose local NVMe disks to QEMU VMs via the vhost-user protocol. However, vhost-user has significant drawbacks: it introduces performance overhead that prevents full utilization of disk capabilities, and it doesn't support NVMe-specific features like NVIDIA GPUDirect Storage (GDS).
To address these limitations, NBS should support exposing local NVMe disks via VFIO-PCI passthrough. This would eliminate the virtualization overhead, enable maximum I/O performance, and provide full access to advanced NVMe features required by GPU-accelerated workloads.

### PR DESCRIPTION
**Pull request by sharpeye**
#5250

### CODE REVIEW

File: cloud/blockstore/libs/nvme/nvme_linux.cpp [hunk 1]
```diff
@@ -591,15 +593,48 @@ class TNvmeManager final
...
+
+        std::span formats(ns.lbaf, ns.nlbaf + 1);
+
+        // Pick the most performant format without metadata
+        auto cmp = [](const auto& lhs, const auto& rhs)
+        {
+            return std::tie(lhs.ms, lhs.rp) < std::tie(rhs.ms, rhs.rp);
+        };
+
+        auto it = std::ranges::min_element(formats, cmp);
```
Comment (dvrazumov) [inline cloud/blockstore/libs/nvme/nvme_linux.cpp:624]: Why `min_element` is most performant?  `.rp` is "relative performance", so here the least performant format is choosed, isn't it?

Comment (dvrazumov) [reply cloud/blockstore/libs/nvme/nvme_linux.cpp:624]: Ouch, turns out that `pr=0` is best performance
