### PR TITLE
various changes in rdma logging and error handling

### LINKED ISSUE #4533: [NBS] Do not call ibv_post_recv in case of an error
```
CRITICAL_EVENT:AppCriticalEvents/RdmaError:RECV 93B246F7.0.169 failed: IBV_WC_RETRY_EXC_ERR
2025-10-15T06:49:33.973431Z :BLOCKSTORE_RDMA ERROR: ibv_post_recv failed with error 12: Cannot allocate memory
```
QP in Error state can't send or receive any packets and any posts will fail

### PR DESCRIPTION
**Pull request by tpashkin**
- resolve #4533
- log completions with unexpected opcodes to debug #3375
- do not throttle unexpected completion messages
- rename unexpected completions -> completion errors
- replace most of the rdma crit events with error messages, because they aren't really all that critical

### CODE REVIEW

File: cloud/blockstore/libs/rdma/impl/server.cpp [hunk 1]
```diff
@@ -602,49 +600,65 @@ bool TServerSession::IsFlushed()
...
+        Counters->CompletionError();
         return;
     }
 
-    // session is closing
-    if (wc->status == IBV_WC_WR_FLUSH_ERR) {
-        HandleFlush(id);
+    if (opcode == IBV_WC_SEND && wc->opcode != IBV_WC_SEND &&
+            wc->opcode != IBV_WC_RDMA_READ && wc->opcode != IBV_WC_RDMA_WRITE ||
+        opcode == IBV_WC_RECV && wc->opcode != IBV_WC_RECV)
```
Comment (budevg) [inline cloud/blockstore/libs/rdma/impl/server.cpp]: let's put parenthesis here around the two `or` expression parts to make it more readable

File: cloud/blockstore/libs/rdma/impl/server.cpp [hunk 2]
```diff
@@ -666,10 +680,7 @@ void TServerSession::HandleCompletionEvent(ibv_wc* wc)
             break;
 
         default:
-            RDMA_ERROR(LogThrottler.Unexpected, Log, "unexpected completion "
-                << NVerbs::PrintCompletion(wc));
-
-            Counters->UnexpectedCompletion();
+            break;
```
Comment (budevg) [inline cloud/blockstore/libs/rdma/impl/server.cpp:684]: you can remove the 
```
default:
  break;
```

File: cloud/blockstore/libs/rdma/impl/server.cpp (hunk 1 above)
Comment (tpashkin) [reply cloud/blockstore/libs/rdma/impl/server.cpp]: It's not going to be readable either way

File: cloud/blockstore/libs/rdma/impl/server.cpp (hunk 2 above)
Comment (tpashkin) [reply cloud/blockstore/libs/rdma/impl/server.cpp:684]: Not really, it won't compile with `-Werror`

File: cloud/blockstore/libs/rdma/impl/server.cpp (hunk 1 above)
Comment (tpashkin) [reply cloud/blockstore/libs/rdma/impl/server.cpp]: Check this out
```cpp
    if ((opcode == IBV_WC_SEND && wc->opcode != IBV_WC_SEND &&
         wc->opcode != IBV_WC_RDMA_READ && wc->opcode != IBV_WC_RDMA_WRITE) ||
        (opcode == IBV_WC_RECV && wc->opcode != IBV_WC_RECV))
```
Can you genuinely say this is more readable?

Comment (budevg) [reply cloud/blockstore/libs/rdma/impl/server.cpp]: it least it doesn't require understanding  operator priority rules ... lets add parenthesis please

Comment (tpashkin) [reply cloud/blockstore/libs/rdma/impl/server.cpp]: Moved validation to it's own function and streamlined it

File: cloud/blockstore/libs/rdma/impl/client.cpp [hunk 3]
```diff
@@ -1028,48 +1031,67 @@ bool TClientEndpoint::HandleCompletionEvents()
...
+        << " " << id << " completed with "
+        << NVerbs::GetStatusString(wc->status));
 
-        Counters->UnexpectedCompletion();
-        return;
-    }
-
-    if (wc->status == IBV_WC_WR_FLUSH_ERR) {
-        HandleFlush(id);
+    if (ValidateCompletion(wc)) {
```
Comment (budevg) [inline cloud/blockstore/libs/rdma/impl/client.cpp:1094]: ValidateCompletion returns -1 if it reclaimed request and 0 if it didn't
do you want it to return `true` in case of reclaim and false in case if ti was not reclaimed? 
Also maybe change the name to `ReclaimInvalidCompletion` ?

Comment (tpashkin) [reply cloud/blockstore/libs/rdma/impl/client.cpp:1094]: > ValidateCompletion returns -1 if it reclaimed request and 0 if it didn't
> do you want it to return true in case of reclaim and false in case if ti was not reclaimed?

We return success (0), if request passed our validation check, and error (-1) if it didn't. Reclaiming work requests is part of the cleanup process

> Also maybe change the name to ReclaimInvalidCompletion ?

It's not the main purpose of this function. What we do, is basically cleaning up and counting errors if something goes wrong
